- build: examples/1-periodic
  photon: [0.7.0, 1.0.0, 1.1.0, 1.2.1-rc.3, 1.3.0-rc.1]
  p1: [1.0.0]
  electron: [1.0.0]
  argon: [0.9.0, 1.1.0]
  boron: [0.8.0-rc.27, 0.9.0, 1.2.1-rc.3, 1.3.0-rc.1]
  xenon: [0.9.0]
- build: examples/2-button-and-timer
  electron: [1.0.0]
- build: examples/3-test-suite
  electron: [1.0.0]

  